version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=meloLibrary
      - MYSQL_ROOT_PASSWORD=123@Password
    volumes:
      - DB:/var/lib/mysql
volumes:
  DB: